const initialTeams = [
    {
        name: "Team 1",
        leader: {
            name: "a",
            branch: "Computer Science",
            collegeName: "IIT Bombay",
            mobileNo: "1234567890",
            rollNo: "1234567890",
            email: "abcd@gmail.com",
            password: "123",
            isLeader: true,
            isAdmin: false, 
            isVerified: true,
        },
        members: [
            {
                name: "a",
                branch: "Computer Science",
                collegeName: "IIT Bombay",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: true,
                isAdmin: false,

                isVerified: true,
            },
            {
                name: "b",
                branch: "Electrical Engineering",
                collegeName: "IIT Delhi",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: false,
                isAdmin: false,

                isVerified: true,
            },
            {
                name: "c",
                branch: "Mechanical Engineering",
                collegeName: "IIT Kanpur",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: false,
                isAdmin: false,

                isVerified: true,
            },
        ],
    },
    {
        name: "Team 2",
        leader: {
            name: "a",
            branch: "Computer Science",
            collegeName: "IIT Bombay",
            mobileNo: "1234567890",
            rollNo: "1234567890",
            email: "abcd@gmail.com",
            password: "123",
            isLeader: true,
            isAdmin: false, 
            isVerified: true,
        },
        members: [
            {
                name: "a",
                branch: "Computer Science",
                collegeName: "IIT Bombay",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: true,
                isAdmin: false,

                isVerified: true,
            },
            {
                name: "b",
                branch: "Electrical Engineering",
                collegeName: "IIT Delhi",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: false,
                isAdmin: false,

                isVerified: true,
            },
            {
                name: "c",
                branch: "Mechanical Engineering",
                collegeName: "IIT Kanpur",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: false,
                isAdmin: false,

                isVerified: true,
            },
        ],
    },
    {
        name: "Team 3",
        leader: {
            name: "a",
            branch: "Computer Science",
            collegeName: "IIT Bombay",
            mobileNo: "1234567890",
            rollNo: "1234567890",
            email: "abcd@gmail.com",
            password: "123",
            isLeader: true,
            isAdmin: false, 
            isVerified: true,
        },
        members: [
            {
                name: "a",
                branch: "Computer Science",
                collegeName: "IIT Bombay",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: true,
                isAdmin: false,

                isVerified: true,
            },
            {
                name: "b",
                branch: "Electrical Engineering",
                collegeName: "IIT Delhi",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: false,
                isAdmin: false,

                isVerified: true,
            },
            {
                name: "c",
                branch: "Mechanical Engineering",
                collegeName: "IIT Kanpur",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: false,
                isAdmin: false,

                isVerified: true,
            },
        ],
    },
    {
        name: "Team 4",
        leader: {
            name: "a",
            branch: "Computer Science",
            collegeName: "IIT Bombay",
            mobileNo: "1234567890",
            rollNo: "1234567890",
            email: "abcd@gmail.com",
            password: "123",
            isLeader: true,
            isAdmin: false, 
            isVerified: true,
        },
        members: [
            {
                name: "a",
                branch: "Computer Science",
                collegeName: "IIT Bombay",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: true,
                isAdmin: false,

                isVerified: true,
            },
            {
                name: "b",
                branch: "Electrical Engineering",
                collegeName: "IIT Delhi",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: false,
                isAdmin: false,

                isVerified: true,
            },
            {
                name: "c",
                branch: "Mechanical Engineering",
                collegeName: "IIT Kanpur",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: false,
                isAdmin: false,

                isVerified: true,
            },
        ],
    },
    {
        name: "Team 5",
        leader: {
            name: "a",
            branch: "Computer Science",
            collegeName: "IIT Bombay",
            mobileNo: "1234567890",
            rollNo: "1234567890",
            email: "abcd@gmail.com",
            password: "123",
            isLeader: true,
            isAdmin: false, 
            isVerified: true,
        },
        members: [
            {
                name: "a",
                branch: "Computer Science",
                collegeName: "IIT Bombay",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: true,
                isAdmin: false,

                isVerified: true,
            },
            {
                name: "b",
                branch: "Electrical Engineering",
                collegeName: "IIT Delhi",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: false,
                isAdmin: false,

                isVerified: true,
            },
            {
                name: "c",
                branch: "Mechanical Engineering",
                collegeName: "IIT Kanpur",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: false,
                isAdmin: false,

                isVerified: true,
            },
        ],
    },
    {
        name: "Team 6",
        leader: {
            name: "a",
            branch: "Computer Science",
            collegeName: "IIT Bombay",
            mobileNo: "1234567890",
            rollNo: "1234567890",
            email: "abcd@gmail.com",
            password: "123",
            isLeader: true,
            isAdmin: false, 
            isVerified: true,
        },
        members: [
            {
                name: "a",
                branch: "Computer Science",
                collegeName: "IIT Bombay",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: true,
                isAdmin: false,

                isVerified: true,
            },
            {
                name: "c",
                branch: "Mechanical Engineering",
                collegeName: "IIT Kanpur",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: false,
                isAdmin: false,

                isVerified: true,
            },
        ],
    },
    {
        name: "Team 7",
        leader: {
            name: "a",
            branch: "Computer Science",
            collegeName: "IIT Bombay",
            mobileNo: "1234567890",
            rollNo: "1234567890",
            email: "abcd@gmail.com",
            password: "123",
            isLeader: true,
            isAdmin: false, 
            isVerified: true,
        },
        members: [
            {
                name: "a",
                branch: "Computer Science",
                collegeName: "IIT Bombay",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: true,
                isAdmin: false,

                isVerified: true,
            },
            {
                name: "b",
                branch: "Electrical Engineering",
                collegeName: "IIT Delhi",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: false,
                isAdmin: false,

                isVerified: true,
            },
            {
                name: "c",
                branch: "Mechanical Engineering",
                collegeName: "IIT Kanpur",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: false,
                isAdmin: false,

                isVerified: true,
            },
        ],
    },
    {
        name: "Team 8",
        leader: {
            name: "a",
            branch: "Computer Science",
            collegeName: "IIT Bombay",
            mobileNo: "1234567890",
            rollNo: "1234567890",
            email: "abcd@gmail.com",
            password: "123",
            isLeader: true,
            isAdmin: false, 
            isVerified: true,
        },
        members: [
            {
                name: "a",
                branch: "Computer Science",
                collegeName: "IIT Bombay",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: true,
                isAdmin: false,

                isVerified: true,
            },
            {
                name: "b",
                branch: "Electrical Engineering",
                collegeName: "IIT Delhi",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: false,
                isAdmin: false,

                isVerified: true,
            },
            {
                name: "c",
                branch: "Mechanical Engineering",
                collegeName: "IIT Kanpur",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: false,
                isAdmin: false,

                isVerified: true,
            },
        ],
    },
    {
        name: "Team 9",
        leader: {
            name: "a",
            branch: "Computer Science",
            collegeName: "IIT Bombay",
            mobileNo: "1234567890",
            rollNo: "1234567890",
            email: "abcd@gmail.com",
            password: "123",
            isLeader: true,
            isAdmin: false,
            isVerified: true,
        },
        members: [
            {
                name: "a",
                branch: "Computer Science",
                collegeName: "IIT Bombay",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: true,
                isAdmin: false,

                isVerified: true,
            },
            {
                name: "b",
                branch: "Electrical Engineering",
                collegeName: "IIT Delhi",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: false,
                isAdmin: false,

                isVerified: true,
            },
            {
                name: "c",
                branch: "Mechanical Engineering",
                collegeName: "IIT Kanpur",
                mobileNo: "1234567890",
                rollNo: "1234567890",
                email: "abcd@gmail.com",
                password: "123",
                isLeader: false,
                isAdmin: false,

                isVerified: true,
            },
        ],
    },
];

// Function to get initial data
const getInitialData = () => initialTeams;

// Function to save teams to localStorage
const saveTeams = (teams) => {
	localStorage.setItem("teams", JSON.stringify(teams));
};

// Function to load teams from localStorage, falling back to initial data
const loadTeams = () => {
	const savedTeams = localStorage.getItem("teams");
	return savedTeams ? JSON.parse(savedTeams) : getInitialData();
};

export const TeamData = {
	getInitialData,
	saveTeams,
	loadTeams,
};
